### ISSUE TITLE
Add option for entering organization name in the create event form

### ISSUE THREAD

**Issue by kriti21** [systers/vms#608] opened 2018-02-10 08:12 UTC
## Description
Refer https://github.com/systers/vms/issues/607

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by kriti21** [comment] 2018-02-10 08:19
I am working on this.

**Comment by kriti21** [comment] 2018-02-12 15:01
@tapasweni-pathak @tonythomas01 I am facing some problem in updating database according to the changed models for issues i am working on. I have tried `python manage.py syncdb` and `python manage.py makemigrations` as well. The sql table using `python manage.py sqlall appname` displays the right changes but internally the added fields are no accessible like in templates or views. Please help with this.

**Comment by tonythomas01** [comment] 2018-02-12 15:06
Can you paste some exact error messages shown ?

**Comment by kriti21** [comment] 2018-02-12 15:17
This is what i get on adding an additional field organization name (foreign key) to the event model.
![error_db](https://user-images.githubusercontent.com/19872082/36103513-8360105a-1035-11e8-8358-5b3234331467.png)

![error_db2](https://user-images.githubusercontent.com/19872082/36103613-dd3ead98-1035-11e8-92a3-31306347f37e.png)

**Comment by anjali-dhanuka** [comment] 2018-02-12 18:17
@kriti21 You can try to manually add the column in the database table itself.
All you need to do is:
open the psql 
1. \c vms
2. ALTER TABLE "Table name" ADD COLUMN "column name" VARCHAR DEFAULT 0;

**Comment by kriti21** [comment] 2018-02-15 06:39
But sql table has already been updated. Only the template rendering part in causing problem. @anjali-dhanuka

**Comment by anjali-dhanuka** [comment] 2018-02-15 06:46
No @kriti21 it is showing that the table columns do not exist which means that the DB has not been updated. Did u try this?

**Comment by anjali-dhanuka** [comment] 2018-03-07 08:00
@kriti21 areu still working on this?

**Comment by anjali-dhanuka** [comment] 2018-03-08 10:01
@abhishekarya286 @ramitsahwney @tapasweni-pathak @kriti21 @tonythomas01 @murad @prachi1210 I don't think that the organisation name has to be entered while creation of an event. While creation of the event, no volunteer is assigned that so which organisation will the administrator enter. Ater all, the events are of systers.

**Comment by ramitsawhney27** [comment] 2018-03-08 19:09
@anjali-dhanuka, yes, you’re right. The problem would still persist if we used the organisation name, however the issue is valid and can be better solved by adding an attribute such as organisation branch which can separate an event with the same name by the same organisation in 2 different cities/locations as they would be organised by different branches. An even better solution would be to simply include an event id and add that to the key for the schema to identify any event uniquely.

**Comment by abhishekarya286** [comment] 2018-03-08 19:26
Agree with Ramit.

**Comment by anjali-dhanuka** [comment] 2018-05-09 03:42
@abhishekarya286 @ayushgarg1804 @ramitsawhney27 @MeepyMay @kamsuri  I guess this issue can be closed, as I have alreaady implemented the solution using the event id.

**Comment by anjali-dhanuka** [comment] 2018-05-13 15:11
Fixed by https://github.com/systers/vms/pull/665

**Closed by anjali-dhanuka** 2018-05-13 15:11 UTC
