### ISSUE TITLE
organizations_list variable scope issue

### ISSUE THREAD

**Issue by mohitkyadav** [systers/vms#633] opened 2018-02-19 11:45 UTC
## Description
As a user,
I want to search volunteers.
Initially the `organizations_list` variable is used in [line-233](https://github.com/systers/vms/blob/develop/vms/volunteer/views.py#L233), this leads to a [UnboundLocalError](https://docs.python.org/2/library/exceptions.html?highlight=unboundlocal#exceptions.UnboundLocalError) at l[ine-250](https://github.com/systers/vms/blob/develop/vms/volunteer/views.py#L250) because the scope of organizations_list is limited inside the conditional statement.

### Changes required
- [ ] initialize `organizations_list` variable outside of the conditional `if-else` statement.

### Note
*I would like to send a pull request, please let me know if I can continue with that.*  😄

**Comment by anjali-dhanuka** [comment] 2018-02-19 16:13
@mohitkyadav Can u please share some mock-ups of the error.

**Comment by sammy1997** [comment] 2018-02-19 18:02
@mohitkyadav Please share a SS of the error

**Comment by mohitkyadav** [comment] 2018-02-19 23:54
Unfortunately I couldn't take the screenshot, I remember the traceback
```
Traceback (most recent call last):
File "volunteer/views.py", line 250
   request, 'volunteer/search.html', {
            'organizations_list': organizations_list,
            'form': form,
            'has_searched': False
        })
UnboundLocalError: local variable 'organizations_list' referenced before assignment
```
 the error appeared only first time, and I fixed that for local testing and when I removed my fix, and the `organizations_list` was initialized in memory so now it's not showing the error.
I don't think you need a screenshot for confirmation, you can tell by looking at the code.

**Comment by sammy1997** [comment] 2018-02-20 08:54
Ok @mohitkyadav . But please wait for the issues to be verified by a mentor before sending PRs, as this was mentioned by @MeepyMay in one of the sessions, that it's against contribution guidelines. :) You can work on your fork and then send a PR later when the issue is verified. Right @MeepyMay ?

**Comment by Monal5031** [comment] 2018-02-21 21:36
@sammy1997 I think this is a valid issue, though it occurs only during the first setup but still it is considered a good practice to declare variables before initialize them.
Your views @MeepyMay ?

**Comment by anjali-dhanuka** [comment] 2018-02-22 10:11
@Monal5031 I'll suggest you to at least insert screenshots of the error while opening an issue in addition to detailed step by step explanation how to produce the error so that others can verify.

**Comment by Monal5031** [comment] 2018-02-22 16:29
@anjali-dhanuka I didn't open this issue, but I'm just supporting the validity of this issue.

**Comment by MeepyMay** [comment] 2018-02-24 20:22
I'm closing this issue. Please update with the issue template. Thanks!

**Closed by MeepyMay** 2018-02-24 20:22 UTC

**Comment by mohitkyadav** [comment] 2018-02-25 02:56
@MeepyMay, updated with the issue template, take a look.
